services:
  - type: web
    name: tarnov-menu
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: tarnov-platform-jwt-2024
      - key: SUPER_ADMIN_EMAIL
        value: admin@tarnov.uz
      - key: SUPER_ADMIN_PASSWORD
        value: superadmin2024
      - key: ADMIN_PASSWORD
        value: tarnov2024
